FROM node:24-alpine AS base

FROM base AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json package-lock.json* .npmrc* ./

RUN \
  if [ -f package-lock.json ]; then npm ci; \
  else echo "Lockfile not found." && exit 1; \
  fi

FROM base AS builder

WORKDIR /app

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_WS_URL
ARG NEXT_PUBLIC_CITRINE_CORE_URL
ARG NEXT_PUBLIC_FILE_SERVER_URL
ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_TENANT_ID
ARG NEXT_PUBLIC_AUTH_PROVIDER
ARG NEXT_PUBLIC_ADMIN_EMAIL
ARG NEXT_PUBLIC_ADMIN_PASSWORD
ARG NEXT_PUBLIC_LOGO_URL
ARG NEXT_PUBLIC_METRICS_URL
ARG NEXT_PUBLIC_DEFAULT_MAP_CENTER_LATITUDE
ARG NEXT_PUBLIC_DEFAULT_MAP_CENTER_LONGITUDE
ARG NEXT_PUBLIC_GOOGLE_MAPS_LOCATION_PICKER_MAP_ID
ARG NEXT_PUBLIC_GOOGLE_MAPS_OVERVIEW_MAP_ID
ARG GOOGLE_MAPS_API_KEY
ARG GOOGLE_MAPS_ADDRESS_API_KEY

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL
ENV NEXT_PUBLIC_CITRINE_CORE_URL=$NEXT_PUBLIC_CITRINE_CORE_URL
ENV NEXT_PUBLIC_FILE_SERVER_URL=$NEXT_PUBLIC_FILE_SERVER_URL
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_TENANT_ID=$NEXT_PUBLIC_TENANT_ID
ENV NEXT_PUBLIC_AUTH_PROVIDER=$NEXT_PUBLIC_AUTH_PROVIDER
ENV NEXT_PUBLIC_ADMIN_EMAIL=$NEXT_PUBLIC_ADMIN_EMAIL
ENV NEXT_PUBLIC_ADMIN_PASSWORD=$NEXT_PUBLIC_ADMIN_PASSWORD
ENV NEXT_PUBLIC_LOGO_URL=$NEXT_PUBLIC_LOGO_URL
ENV NEXT_PUBLIC_METRICS_URL=$NEXT_PUBLIC_METRICS_URL
ENV NEXT_PUBLIC_DEFAULT_MAP_CENTER_LATITUDE=$NEXT_PUBLIC_DEFAULT_MAP_CENTER_LATITUDE
ENV NEXT_PUBLIC_DEFAULT_MAP_CENTER_LONGITUDE=$NEXT_PUBLIC_DEFAULT_MAP_CENTER_LONGITUDE
ENV NEXT_PUBLIC_GOOGLE_MAPS_LOCATION_PICKER_MAP_ID=$NEXT_PUBLIC_GOOGLE_MAPS_LOCATION_PICKER_MAP_ID
ENV NEXT_PUBLIC_GOOGLE_MAPS_OVERVIEW_MAP_ID=$NEXT_PUBLIC_GOOGLE_MAPS_OVERVIEW_MAP_ID
ENV GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY
ENV GOOGLE_MAPS_ADDRESS_API_KEY=$GOOGLE_MAPS_ADDRESS_API_KEY

COPY --from=deps /app/node_modules ./node_modules

COPY . .

RUN npm run build

FROM base AS runner

WORKDIR /app

ENV NODE_ENV=production

# Create a non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

RUN mkdir .next
RUN chown nextjs:nodejs .next

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]